project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Statistics"
  author: "Yuzu Sensei"
  date: "today"
  chapters:
    - index.qmd
    - Sampling.qmd
    - Confidence.qmd
    - Hypothesis.qmd
    - Upcoming.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    number-depth: 3
    #html-math-method: katex
  pdf:
   documentclass: scrreprt

editor: visual
