# Basics

## Descriptive Statistics

population deviation

$$
\sigma=\sqrt{\frac{\sum_{i=1}^N (X_i-\mu)^2}{N}}
$$

standard deviation of a sample

$$
s=\sqrt{\frac{\sum_{i=1}^n (X_i-\mu)^2}{n-1}}
$$

is descriptive statistics, which is a description of the variation in measurements. However, the standard error of the mean is descriptive of the random sampling process, which is a probabilistic statement about how the sample size will provide a better bound on estimates of the population mean, in light of the central limit theorem.

For a sample of size $n$,

standard deviation of the sample mean

$$
s.d(\bar{X}) = \frac{\sigma}{\sqrt{n}}
$$

but since $\sigma$ is unknow, we use standard error of the sample mean

$$
s.e(\bar{X})=\frac{s}{\sqrt{n}}
$$

Put simply, the **standard error** of the sample mean is an estimate of how far the sample mean is likely to be from the population mean, whereas the **standard deviation** of the sample is the degree to which individuals within the sample differ from the sample mean.^[\[9\]](https://en.wikipedia.org/wiki/Standard_error#cite_note-9)^ If the population standard deviation is finite, the standard error of the mean of the sample will tend to zero ($s.e\to 0$ )with increasing sample size, because the estimate of the population mean will improve, while the standard deviation of the sample $s$ will tend to approximate the population standard deviation $\sigma$ as the sample size increases.

## Confidence interval

Suppose $X_1,...,X_n$ is an independent sample from a population $Normal(\mu,\sigma^2)$.

Sample mean

$$
\bar{X} = \frac{X_1+...+X_n}{n}
$$

Sample variance

$$
s^2=\frac{1}{n-1}\sum_{i=1}^n (X_i-\bar{X})^2
$$

Then

$$
T=\frac{\bar{X}-\mu}{\frac{S}{\sqrt{n}}}=\frac{\bar{X}-\mu}{s.e}
$$

s.e is the standard error of the sample mean

## Randomisation

How can we use sampled data to inform us about the population from which the data are drawn?

Suppose that $X_1,X_2,...,X_n$ represent a random sample from a distribution with mean $\mu$ , then

$$
E[X_1+X_2+...+X_n]=E[X_1]+E[X_2]+...+E[X_n]=n\mu.
$$

Since $X_1,X_2,...,X_n$ are independent (hence uncorrelated), we have

$$
\text{Var}(X_1+X_2+...+X_n)=\text{Var}(X_1)+\text{Var}(X_2)+...+\text{Var}(X_n)=n\sigma^2
$$

$$
\begin{aligned}
\text{sd}(X_1+X_2+...+X_n)&=\sqrt{\text{Var}(X_1+X_2+...+X_n)}\\
&=\sqrt{\text{Var}(X_1)+\text{Var}(X_2)+...+\text{Var}(X_n)}\\
&=\sqrt{n\sigma^2}=\sqrt{n} \sigma 
\end{aligned}
$$

